#include <algorithm>
#include <cmath>
#include <climits>
#include <functional>
#include <iostream>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
using namespace std;
struct T{int w,u,v,e;};
int S0,W,Acount,Bcount,D,qmax; vector<T> types; vector<vector<pair<T,int>>> dists; long long graphs=0,surv=0; vector<string> outputs;
int rankmod(long long Q[12][12],int p){int A[12][12];for(int i=0;i<12;i++)for(int j=0;j<12;j++)A[i][j]=(Q[i][j]%p+p)%p;int r=0;for(int c=0;c<12;c++){int z=-1;for(int i=r;i<12;i++)if(A[i][c]){z=i;break;}if(z<0)continue;for(int j=0;j<12;j++)swap(A[r][j],A[z][j]);int x=A[r][c],inv=1,e=p-2;for(;e;e>>=1,x=(long long)x*x%p)if(e&1)inv=(long long)inv*x%p;for(int j=c;j<12;j++)A[r][j]=(long long)A[r][j]*inv%p;for(int i=0;i<12;i++)if(i!=r&&A[i][c]){int f=A[i][c];for(int j=c;j<12;j++)A[i][j]=(A[i][j]-(long long)f*A[r][j]%p+p)%p;}r++;}return r;}
long long detbareiss(long long Q0[12][12]){__int128 A[12][12];for(int i=0;i<12;i++)for(int j=0;j<12;j++)A[i][j]=Q0[i][j];__int128 prev=1;int sign=1;for(int k=0;k<11;k++){int z=k;while(z<12&&A[z][k]==0)z++;if(z==12)return 0;if(z!=k){for(int j=0;j<12;j++)swap(A[k][j],A[z][j]);sign=-sign;}__int128 piv=A[k][k];for(int i=k+1;i<12;i++)for(int j=k+1;j<12;j++)A[i][j]=(A[i][j]*piv-A[i][k]*A[k][j])/prev;prev=piv;}__int128 d=A[11][11]*sign;if(d>LLONG_MAX||d<LLONG_MIN){cerr<<"overflow\n";exit(3);}return (long long)d;}
bool squarell(long long x){if(x<0)return false;long long r=sqrt((long double)x);while((__int128)r*r<x)r++;while((__int128)r*r>x)r--;return (__int128)r*r==x;}
void enumD(int i,int left,int sw,int su,int sv,int se,vector<pair<T,int>>&cur){if(i==(int)types.size()){if(left==0&&sw==S0*W&&su==5*Acount&&sv==6*Bcount&&se==2*D)dists.push_back(cur);return;}T t=types[i];for(int c=0;c<=left;c++){if(sw+c*t.w>S0*W||su+c*t.u>5*Acount||sv+c*t.v>6*Bcount||se+c*t.e>2*D)continue;if(c)cur.push_back({t,c});enumD(i+1,left-c,sw+c*t.w,su+c*t.u,sv+c*t.v,se+c*t.e,cur);if(c)cur.pop_back();}}
int adjm[12][12];vector<T> verts;
void test(int di){graphs++;long long Q[12][12];for(int i=0;i<12;i++)for(int j=0;j<12;j++)Q[i][j]=(i==j?verts[i].w+verts[i].u+verts[i].v:2-adjm[i][j]);bool ok=1;if(qmax<12){for(int p:{101,103,107})if(rankmod(Q,p)>qmax){ok=0;break;}}else if(qmax==12){if(!squarell(detbareiss(Q)))ok=0;}if(ok){surv++;ostringstream o;o<<"{\"dist\":"<<di<<",\"types\":[";for(int i=0;i<12;i++){if(i)o<<",";o<<"["<<verts[i].w<<","<<verts[i].u<<","<<verts[i].v<<","<<verts[i].e<<"]";}o<<"],\"edges\":[";bool f=1;for(int i=0;i<12;i++)for(int j=i+1;j<12;j++)if(adjm[i][j]){if(!f)o<<",";f=0;o<<"["<<i<<","<<j<<","<<adjm[i][j]<<"]";}o<<"]}";outputs.push_back(o.str());}}
void enumG(vector<int>d,int di){int i=-1;for(int k=0;k<12;k++)if(d[k]){i=k;break;}if(i<0){test(di);return;}vector<int>js;for(int j=i+1;j<12;j++)if(d[j])js.push_back(j);vector<int>xs(js.size());function<void(int,int)> rec=[&](int k,int left){if(k==(int)js.size()){if(left)return;auto nd=d;nd[i]=0;for(int z=0;z<(int)js.size();z++){nd[js[z]]-=xs[z];adjm[i][js[z]]=adjm[js[z]][i]=xs[z];if(nd[js[z]]<0){for(int y=0;y<=z;y++)adjm[i][js[y]]=adjm[js[y]][i]=0;return;}}enumG(nd,di);for(int z=0;z<(int)js.size();z++)adjm[i][js[z]]=adjm[js[z]][i]=0;return;}int j=js[k];for(int x=0;x<=min({2,d[j],left});x++){xs[k]=x;rec(k+1,left-x);}};rec(0,d[i]);}
int main(int argc,char**argv){if(argc!=7){cerr<<"usage: s0 W a b D outmode\n";return 2;}S0=stoi(argv[1]);W=stoi(argv[2]);Acount=stoi(argv[3]);Bcount=stoi(argv[4]);D=stoi(argv[5]);qmax=W+Acount+Bcount;for(int w=0;w<=W;w++)for(int u=0;u<=Acount;u++)for(int v=0;v<=Bcount;v++){int e=22-(S0-1)*w-4*u-5*v;if(0<=e&&e<=D)types.push_back({w,u,v,e});}vector<pair<T,int>>cur;enumD(0,12,0,0,0,0,cur);for(int di=0;di<(int)dists.size();di++){verts.clear();for(auto [t,c]:dists[di])for(int z=0;z<c;z++)verts.push_back(t);sort(verts.begin(),verts.end(),[](T a,T b){if(a.e!=b.e)return a.e>b.e;int qa=a.w+a.u+a.v,qb=b.w+b.u+b.v;if(qa!=qb)return qa>qb;if(a.w!=b.w)return a.w>b.w;if(a.u!=b.u)return a.u>b.u;return a.v>b.v;});vector<int>d;for(auto t:verts)d.push_back(t.e);enumG(d,di);}cout<<"{\"s0\":"<<S0<<",\"w\":"<<W<<",\"a\":"<<Acount<<",\"b\":"<<Bcount<<",\"D\":"<<D<<",\"dists\":"<<dists.size()<<",\"graphs\":"<<graphs<<",\"survivors\":"<<surv<<",\"cases\":[";for(int i=0;i<(int)outputs.size();i++){if(i)cout<<",";cout<<outputs[i];}cout<<"]}\n";}
